# Created by newuser for 5.0.7

# direnv
eval "$(direnv hook zsh)"

alias ls='ls -aFG'
alias ll='ls -alFG'

function gcd() {
  local selected=$(ghq list --unique | peco)
  #BUFFER=$selected
  if [ -n "$selected" ]; then
    ghq look $selected
  fi
}

