#!/bin/bash

##
## Uninstall Homebrew 
##
## @see  https://gist.github.com/mxcl/1173223

curl -s https://gist.githubusercontent.com/mxcl/1173223/raw/a833ba44e7be8428d877e58640720ff43c59dbad/uninstall_homebrew.sh | sh

